name: IG Reels Reposter

on:
  schedule:
    - cron: "0 8 * * *"  # Every day at 8:00 AM UTC
  workflow_dispatch:

jobs:
  run-reposter:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{EAANZCBW5j6L8BPMoF1Fb7mVnzVp8QkA2j3pZAvKDikB1Y5rlubiKopZCXtZCc0ZBJoAIJq0XQem5S2DmQbOZAcThMGD8mGWbKjZAKHouvZBmSGNNTlsAnPTS2qMJjwy9ZCoWOWdzl7JuIugNrHyUEmCV2OM2pKqyW6cX1gD8VW03pECZBUh9Ikp8me4WuN3fND6hbH }}
      IG_USER_ID: ${{17841412345678901 }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        run: python main.py
